<?php

$this->tag->appendTitle(' - Admin for phalcon modular application');

$this->assets->collection('js')->addJs('vendor/bootstrap/js/bootstrap.min.js');

$this->assets->collection('css')->addCss('vendor/bootstrap/css/bootstrap.min.css');

?><!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {{ get_title() }}
        <?php $this->assets->outputCss('css') ?>
        <?php $this->assets->outputCss('cssMin') ?>
        <?php $this->assets->outputJs('js') ?>
    </head>
    <body>
        <header class="container">
            {{ partial("main/header") }}
        </header>
        <div class="container">
            {{ content() }}
        </div>
        <footer class="container">
            {{ partial("main/footer") }}
        </footer>
        <?php $this->assets->outputJs('jsMin') ?>
    </body>
</html>